export const groups = [
  {
    id: '1',
    name: 'Youth Parliament: Lviv–Omaha',
    description: 'Students from Ukraine and Nebraska co-create policy proposals on climate, democracy, and human rights — then present to real decision-makers.',
    category: 'Youth Exchange',
    categoryColor: '#E8A838',
    memberCount: 47,
    activeToday: true,
    cover: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 40%, #0f3460 100%)',
    icon: '🌍',
    location: 'Lviv, UA · Omaha, US',
    recentActivity: '2 hours ago',
    organizers: ['Maya Chen', 'Dmytro Kovalenko', 'Sarah Mills'],
  },
  {
    id: '2',
    name: 'Climate Futures: Nairobi–Copenhagen',
    description: 'Cross-continental youth climate scientists mapping local environmental data and building shared solutions across two very different worlds.',
    category: 'Climate Action',
    categoryColor: '#4CAF7D',
    memberCount: 62,
    activeToday: true,
    cover: 'linear-gradient(135deg, #0d2818 0%, #1a4731 40%, #0d3320 100%)',
    icon: '🌱',
    location: 'Nairobi, KE · Copenhagen, DK',
    recentActivity: '45 minutes ago',
    organizers: ['Aisha Mwangi', 'Lars Eriksson'],
  },
  {
    id: '3',
    name: 'Civic Tech Fellows',
    description: 'High schoolers and college students building digital tools for civic engagement — from voter guides to neighborhood mapping apps.',
    category: 'Civic Tech',
    categoryColor: '#7B68EE',
    memberCount: 31,
    activeToday: false,
    cover: 'linear-gradient(135deg, #1a0a2e 0%, #2d1b69 40%, #1a0a3e 100%)',
    icon: '⚡',
    location: 'Global',
    recentActivity: '1 day ago',
    organizers: ['Jordan Park', 'Priya Nair'],
  },
  {
    id: '4',
    name: 'Ocean Stories: Pacific Voices',
    description: 'Island youth documenting their changing coastlines through photography, mapping, and storytelling — creating an archive for climate science.',
    category: 'Environment',
    categoryColor: '#38B2E8',
    memberCount: 28,
    activeToday: true,
    cover: 'linear-gradient(135deg, #0a1628 0%, #0d2a4a 40%, #0a1f3c 100%)',
    icon: '🌊',
    location: 'Fiji · Hawaii · Philippines',
    recentActivity: '3 hours ago',
    organizers: ['Tala Faleolo', 'Kenji Nakamura'],
  },
  {
    id: '5',
    name: 'Arts Without Borders',
    description: 'Young artists from conflict zones and stable democracies creating collaborative work that crosses language, culture, and politics.',
    category: 'Arts & Culture',
    categoryColor: '#E85592',
    memberCount: 54,
    activeToday: false,
    cover: 'linear-gradient(135deg, #2a0a1e 0%, #4a1535 40%, #2a0a28 100%)',
    icon: '🎨',
    location: 'Global',
    recentActivity: '2 days ago',
    organizers: ['Fatima Al-Rashid', 'Marco Rossi', 'Zoe Williams'],
  },
  {
    id: '6',
    name: 'Future Cities Lab',
    description: 'Urban youth redesigning their neighborhoods — mapping infrastructure gaps, proposing solutions, and presenting to city planners.',
    category: 'Urban Design',
    categoryColor: '#E88338',
    memberCount: 39,
    activeToday: true,
    cover: 'linear-gradient(135deg, #1a1208 0%, #3d2c10 40%, #2a1e08 100%)',
    icon: '🏙️',
    location: 'São Paulo · Detroit · Lagos',
    recentActivity: '5 hours ago',
    organizers: ['Carlos Mendez', 'Amara Osei'],
  },
];

export const members = [
  { id: '1', name: 'Maya Chen', role: 'Organizer', location: 'Omaha, US', flag: '🇺🇸', avatar: 'MC', color: '#E8A838', groups: 3, joined: 'Sep 2023' },
  { id: '2', name: 'Dmytro Kovalenko', role: 'Organizer', location: 'Lviv, UA', flag: '🇺🇦', avatar: 'DK', color: '#4CAF7D', groups: 2, joined: 'Oct 2023' },
  { id: '3', name: 'Aisha Mwangi', role: 'Member', location: 'Nairobi, KE', flag: '🇰🇪', avatar: 'AM', color: '#38B2E8', groups: 2, joined: 'Jan 2024' },
  { id: '4', name: 'Lars Eriksson', role: 'Organizer', location: 'Copenhagen, DK', flag: '🇩🇰', avatar: 'LE', color: '#7B68EE', groups: 1, joined: 'Jan 2024' },
  { id: '5', name: 'Jordan Park', role: 'Member', location: 'Seoul, KR', flag: '🇰🇷', avatar: 'JP', color: '#E85592', groups: 1, joined: 'Mar 2024' },
  { id: '6', name: 'Priya Nair', role: 'Organizer', location: 'Mumbai, IN', flag: '🇮🇳', avatar: 'PN', color: '#E88338', groups: 2, joined: 'Feb 2024' },
  { id: '7', name: 'Tala Faleolo', role: 'Member', location: 'Suva, FJ', flag: '🇫🇯', avatar: 'TF', color: '#4CAF7D', groups: 1, joined: 'Apr 2024' },
  { id: '8', name: 'Fatima Al-Rashid', role: 'Organizer', location: 'Amman, JO', flag: '🇯🇴', avatar: 'FA', color: '#E8A838', groups: 1, joined: 'Jun 2024' },
  { id: '9', name: 'Carlos Mendez', role: 'Member', location: 'São Paulo, BR', flag: '🇧🇷', avatar: 'CM', color: '#38B2E8', groups: 2, joined: 'May 2024' },
  { id: '10', name: 'Sarah Mills', role: 'Teacher', location: 'Omaha, US', flag: '🇺🇸', avatar: 'SM', color: '#7B68EE', groups: 3, joined: 'Sep 2023' },
  { id: '11', name: 'Kenji Nakamura', role: 'Member', location: 'Tokyo, JP', flag: '🇯🇵', avatar: 'KN', color: '#E85592', groups: 1, joined: 'Jul 2024' },
  { id: '12', name: 'Amara Osei', role: 'Organizer', location: 'Accra, GH', flag: '🇬🇭', avatar: 'AO', color: '#E88338', groups: 1, joined: 'Aug 2024' },
];

export const activities = [
  { id: '1', member: members[0], action: 'started a discussion', target: '"What does democracy look like in 2025?"', group: groups[0], time: '2h ago', type: 'discussion' },
  { id: '2', member: members[1], action: 'shared a route', target: '"Historic Lviv Walking Tour"', group: groups[0], time: '3h ago', type: 'route' },
  { id: '3', member: members[2], action: 'uploaded a document', target: '"Nairobi Climate Data 2024"', group: groups[1], time: '5h ago', type: 'document' },
  { id: '4', member: members[3], action: 'joined the group', target: '', group: groups[1], time: '6h ago', type: 'join' },
  { id: '5', member: members[4], action: 'started a discussion', target: '"Mapping civic tech gaps in our city"', group: groups[2], time: '1d ago', type: 'discussion' },
  { id: '6', member: members[6], action: 'uploaded a document', target: '"Coastal erosion photo essay"', group: groups[3], time: '1d ago', type: 'document' },
  { id: '7', member: members[7], action: 'shared a route', target: '"Art spaces in Amman"', group: groups[4], time: '2d ago', type: 'route' },
  { id: '8', member: members[8], action: 'started a discussion', target: '"Favela infrastructure project update"', group: groups[5], time: '2d ago', type: 'discussion' },
];

export const discussions = [
  { id: '1', title: 'What does democracy look like in 2025?', author: members[0], replies: 14, members: 8, lastActivity: '2h ago', tags: ['democracy', 'policy'], pinned: true },
  { id: '2', title: 'Mapping our neighborhoods — first results', author: members[1], replies: 7, members: 5, lastActivity: '4h ago', tags: ['maps', 'data'], pinned: false },
  { id: '3', title: 'Cross-border youth summit — who wants to join?', author: members[9], replies: 23, members: 12, lastActivity: '1d ago', tags: ['events', 'summit'], pinned: false },
  { id: '4', title: 'Resource: How to present to city council', author: members[9], replies: 5, members: 4, lastActivity: '2d ago', tags: ['resources', 'civic'], pinned: false },
  { id: '5', title: 'Introducing myself — from Lviv', author: members[1], replies: 18, members: 9, lastActivity: '3d ago', tags: ['introductions'], pinned: false },
  { id: '6', title: 'Live discussion recap — April session', author: members[0], replies: 4, members: 6, lastActivity: '5d ago', tags: ['recap'], pinned: false },
];

export const events = [
  { id: '1', title: 'Virtual Summit: Youth & Climate Policy', group: groups[1], date: 'Jun 18', time: '3:00 PM UTC', attendees: 34 },
  { id: '2', title: 'Map Workshop: Plotting Your Neighborhood', group: groups[5], date: 'Jun 20', time: '5:00 PM UTC', attendees: 18 },
  { id: '3', title: 'Lviv–Omaha Live Exchange Session', group: groups[0], date: 'Jun 25', time: '2:00 PM UTC', attendees: 41 },
  { id: '4', title: 'Civic Tech Demo Day', group: groups[2], date: 'Jul 3', time: '4:00 PM UTC', attendees: 27 },
];

export const routes = [
  { id: '1', title: 'Historic Lviv Walking Tour', author: members[1], distance: '4.2 km', group: groups[0] },
  { id: '2', title: 'Nairobi Green Spaces Map', author: members[2], distance: '12.8 km', group: groups[1] },
  { id: '3', title: 'Omaha Civic Sites', author: members[0], distance: '6.1 km', group: groups[0] },
  { id: '4', title: 'São Paulo Favela Infrastructure', author: members[8], distance: '3.4 km', group: groups[5] },
  { id: '5', title: 'Copenhagen Climate Tour', author: members[3], distance: '8.7 km', group: groups[1] },
  { id: '6', title: 'Art Spaces in Amman', author: members[7], distance: '5.2 km', group: groups[4] },
];
